name: cron

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "*/10 * * * *"

jobs:
  send:
    runs-on: ubuntu-20.04
    environment:
      name: production

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: go run
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          BIRTH_DATE: ${{ secrets.BIRTH_DATE }}
          CHAT_ID: ${{ secrets.CHAT_ID}}
        run: go run main.go
